### ISSUE TITLE
Needs startup recipes created.

### ISSUE THREAD

**Issue by gary-conlon** [bennyb1971/Blue-Sky#3]
**Astral Sorcery** - Rock crystal ore needs to be implemented in some way.
**Embers** - The Ember material needs to be implemented in some way.
**Bees** - No way to actually get bees. Maybe add outputs from leaves to get the startup bees

**Comment by bennyb1971** [comment]
**Astral Sorcery :**  to be worked on
**Ember:**  to be worked on
**Bees:**  added in dev

**Comment by bennyb1971** [comment]
**Astral Sorcery :** added in dev
**Embers :** to be worked on
**Bees:**  added in dev

**Comment by bennyb1971** [comment]
**Astral Sorcery :** added in dev
**Embers :** added in dev
**Bees:** added in dev
