### ISSUE TITLE
Weird Generation

### ISSUE THREAD

**Issue by gary-conlon** [bennyb1971/Blue-Sky#4]
Build craft oil generates
Natura thornvines generate in the nether

**Comment by bennyb1971** [comment]
Weird that buildcraft oil generates there. its disabled in the config

worldgen {
    # Should BuildCraft generate anything in the world?
    B:enable=false

    # Should any oil sprouts or lakes be generated at all?
    B:enableOilGen=false

    # Whether oil spouts are generated or not. The oil spring at the bottom of large lakes will still exist.
    B:enableOilSpouts=false

    # Biome registry names (e.g. 'minecraft:ocean','minecraft:plains') of biomes that should have GREATLY increased oil generation rates.
    S:excessiveBiomes <
        buildcraftenergy:oil_desert
        buildcraftenergy:oil_ocean
     >

    # Biome registry names (e.g. 'minecraft:hell','minecraft:jungle') of biomes that should never generate oil.
    S:excludedBiomes <
        minecraft:hell
        minecraft:sky
     >

    # Dimension ID's (e.g. '-1' for the nether,'1' for the end) of dimensions that should never generate oil.
    I:excludedDimensions <
        -1
        1
     >

**Comment by bennyb1971** [comment]
Natura thornvines disabled in configs
