### ISSUE TITLE
Wooden Hammer recipe is hosed up

### ISSUE THREAD

**Issue by Sabster** [bennyb1971/Blue-Sky#5]
Instead of a wooden hammer, it shows some sort of wooden wrench.  The rest (stone hammer, etc...) seem to be fine...

**Comment by LazyFlesh** [comment]
yea, it auomatically changes the recipe so it takes 4 wood instead of 2 in an L shape

**Comment by bennyb1971** [comment]
Will look into it asap

**Comment by bennyb1971** [comment]
added the no more recipe conflict mod so you can go thru the different recipes in the crafting station (it shows a button with an arrow on the right side of the gui and it says how many items can be crafted with that recipe)
